testapp2/core/urls.py
from django.conf.urls import include, url


from .views import ArtigoUpdateView, ArtigoCreateView, ArtigoListView, RevisionView, RevisionView2, \
    ArtigoVersionListView

urlpatterns = [
    url(r'^list/$', ArtigoListView.as_view(), name='artigo_list'),
    url(r'^create/$', ArtigoCreateView.as_view(), name='artigo_create'),
    url(r'^update/(?P<pk>\d+)/$', ArtigoUpdateView.as_view(), name='artigo_update'),
    url(r'^revision/(?P<pk>\d+)/$', RevisionView.as_view(), name='artigo_revison'),
    url(r'^revision2/(?P<pk>\d+)/$', RevisionView2.as_view(), name='artigo_revison3'),
    url(r'^revision3/(?P<pk>\d+)/$', ArtigoVersionListView.as_view(), name='artigo_revison2')


]

testapp2/testapp2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views import generic

# from wiki.urls import get_pattern as get_wiki_pattern
# from django_nyt.urls import get_pattern as get_nyt_pattern

from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^notifications/', get_nyt_pattern()),
    # url(r'', get_wiki_pattern()),
    url(r'^$', generic.TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^redactor/', include('redactor.urls')),
    url('^', include('django.contrib.auth.urls')),

]

# from django.apps import apps
#
# if apps.is_installed('core'):
#     urlpatterns += [
#         url(r'', include('core.urls')),
#     ]

testapp2/documentos/models.py
from django.db import models
from django.utils.timezone import now

from redactor.fields import RedactorField
import reversion


class TimeStamped(models.Model):
    """
    Provides created and updated timestamps on models.
    """

    class Meta:
        abstract = True

    created = models.DateTimeField(null=True, editable=False)
    updated = models.DateTimeField(null=True, editable=False)

    def save(self, *args, **kwargs):
        _now = now()
        self.updated = _now
        if not self.id:
            self.created = _now
        super(TimeStamped, self).save(*args, **kwargs)


class AbstractDocumento(models.Model):
    conteudo = RedactorField()

    class Meta:
        abstract = True


class Documento(models.Model):
    pass


reversion.register(Documento)

testapp2/templates/base_template.html
{% extends "blank.html" %}

{% block navbar %}
{% endblock navbar %}

{% block masterconteudo %}
    <h1 class="page-header">Blank</h1>
    {% if user.is_authenticated %}
        <p>Bem vindo, <b>{{ user.username }}</b>. Fazer <a class="btn btn-danger btn-xs"
                                                           href="{% url "logout" %}">logout</a></p>
        <p></p>
        {% block conteudo %}
        {% endblock %}
    {% else %}
        <p>Please <a href="{% url "login" %}">login</a> to see this page.</p>
    {% endif %}

{% endblock masterconteudo %}

testapp2/templates/blank.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>APP TESTE</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "bower_components/bootstrap/dist/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static "bower_components/metisMenu/dist/metisMenu.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "sb-admin2/css/sb-admin-2.css" %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static "bower_components/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top"  role="navigation" style="margin-bottom: 0">
        {% block navbar %}

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">SB Admin v2.0</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Charts<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="flot.html">Flot Charts</a>
                                </li>
                                <li>
                                    <a href="morris.html">Morris.js Charts</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="tables.html"><i class="fa fa-table fa-fw"></i> Tables</a>
                        </li>
                        <li>
                            <a href="forms.html"><i class="fa fa-edit fa-fw"></i> Forms</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-wrench fa-fw"></i> UI Elements<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="panels-wells.html">Panels and Wells</a>
                                </li>
                                <li>
                                    <a href="buttons.html">Buttons</a>
                                </li>
                                <li>
                                    <a href="notifications.html">Notifications</a>
                                </li>
                                <li>
                                    <a href="typography.html">Typography</a>
                                </li>
                                <li>
                                    <a href="icons.html"> Icons</a>
                                </li>
                                <li>
                                    <a href="grid.html">Grid</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-sitemap fa-fw"></i> Multi-Level Dropdown<span
                                    class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="#">Second Level Item</a>
                                </li>
                                <li>
                                    <a href="#">Second Level Item</a>
                                </li>
                                <li>
                                    <a href="#">Third Level <span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <li>
                                            <a href="#">Third Level Item</a>
                                        </li>
                                        <li>
                                            <a href="#">Third Level Item</a>
                                        </li>
                                        <li>
                                            <a href="#">Third Level Item</a>
                                        </li>
                                        <li>
                                            <a href="#">Third Level Item</a>
                                        </li>
                                    </ul>
                                    <!-- /.nav-third-level -->
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li class="active">
                            <a href="#"><i class="fa fa-files-o fa-fw"></i> Sample Pages<span
                                    class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a class="active" href="blank.html">Blank Page</a>
                                </li>
                                <li>
                                    <a href="login.html">Login Page</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
        {% endblock navbar %}
        <!-- /.navbar-static-side -->
    </nav>

    <!-- Page Content -->
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    {% block masterconteudo %}

                    {% endblock masterconteudo %}
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

<!-- jQuery -->
<script src="{% static "bower_components/jquery/dist/jquery.min.js" %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static "bower_components/bootstrap/dist/js/bootstrap.min.js" %}"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="{% static "bower_components/metisMenu/dist/metisMenu.min.js" %}"></script>

<!-- Custom Theme JavaScript -->
<script src="{% static "sb-admin2/js/sb-admin-2.js" %}"></script>

</body>

</html>

testapp2/templates/index.html
{% extends "base_template.html" %}


{% block conteudo %}
    <div class="ui list">
        <div class="item">
            <a class="header" href="{% url "documentos:documento_create" %}">Cadastrar Novo documento</a>
            <div class="description">
               Vai para a pagina de cadastro de documento chatos
            </div>
        </div>

        <div class="item">
            <a class="header" href="{% url "documentos:documento_list" %}">Listar documentos</a>
            <div class="description">
               Vai para a pagina que lista documentos chatos
            </div>
        </div>

    </div>

{% endblock conteudo %}